### ISSUE TITLE
Adding a Quick point from Tasker

### ISSUE THREAD

**Issue by sik0vny** [Falcosc/locus-addon-tasker#12]
Hi.
Is there a way to implement **Add a Quick new point** in current Locus API?

I would like to create a Locus task, that will just add a certain Quick point from my list of predefined Quick points.

**Comment by Falcosc** [comment]
@sik0vny sorry for my late response. Active development will be around the winter time when I have less outdoor hobbies :)

I remember an API function which allows creating points on specific coordinates.

But I bet you won't get any locus dialogs popping up, so you would need to collect any point information, like position and meta information by your own inside tasker.

Would this fit you or does your idea require any locus dialog window?

**Comment by Falcosc** [comment]
@sik0vny Would this fit you or does your idea require any locus dialog window?

**Comment by Maksim8868** [comment]
Hello! help me please. How can I configure the addition of a quick point via bluetooz remote controller and tasker?     https://aliexpress.ru/item/4001240613825.html?spm=a2g0o.productlist.0.0.51cb2fc1BR2VFh&algo_pvid=cd1376f6-6abb-434f-a7d5-74ea33de8ca3&algo_expid=cd1376f6-6abb-434f-a7d5-74ea33de8ca3-51&btsid=0b8b034a16152794847006710e0a0e&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_                                   https://aliexpress.ru/item/1005002091499653.html?spm=a2g0o.productlist.0.0.51cb2fc1BR2VFh&algo_pvid=105e9351-1f0a-4160-87e6-efdfa6b4651b&algo_expid=105e9351-1f0a-4160-87e6-efdfa6b4651b-1&btsid=0b8b034a16152792649675777e0a0e&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_                    https://aliexpress.ru/item/1005002070398355.html?spm=a2g0o.productlist.0.0.51cb2fc1BR2VFh&algo_pvid=d4e50b2f-b8cf-4910-ac03-6d7a684edf06&algo_expid=d4e50b2f-b8cf-4910-ac03-6d7a684edf06-35&btsid=0b8b034a16152793295566050e0a0e&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_&sku_id=12000018635699482                         https://aliexpress.ru/item/4001010727504.html?spm=a2g0o.productlist.0.0.51cb2fc1BR2VFh&algo_pvid=e7441771-7e1a-437c-9544-6f35c63e1ffd&algo_expid=e7441771-7e1a-437c-9544-6f35c63e1ffd-1&btsid=0b8b034a16152794274746480e0a0e&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_&sku_id=10000013438486694                   https://aliexpress.ru/item/32834948900.html?spm=a2g0o.productlist.0.0.51cb2fc1BR2VFh&algo_pvid=cd1376f6-6abb-434f-a7d5-74ea33de8ca3&algo_expid=cd1376f6-6abb-434f-a7d5-74ea33de8ca3-16&btsid=0b8b034a16152794847006710e0a0e&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_&sku_id=65143676562

**Comment by Falcosc** [comment]
@Maksim8868 Did you already create a Task which reacts to the Bluetooth remote Controller button press?

So are you able to create a simple "Alert" on Button press task?

If yes, then I can help you to replace the "Alert" with "Save current Location as Waypoint"

**Comment by Maksim8868** [comment]
Thank you for attention. I will be able to create a "Alert" task when a button is clicked. Please indicate the name of the team.

**Comment by Falcosc** [comment]
Cool, so your part is done there.

I don't know how the API does behave. So before I implement it I would like to know if the worst case scenario still would be useful for you. I did already ask @sik0vny this question but didn't get a response. So I did stop there to prevent wasting time implementing something which does not cover your use cases :)

Would it be enough for your solution if the point creation:
- does not open any UI in Locus and you would need all to enter all your inputs via tasker
- does force a locus dialog during point creation (not sure how easy it would be to close a locus dialog via tasker)
- don't allow any data input and generates generic point names

**Comment by Maksim8868** [comment]
Мне это не важно. Только создание  точек без номеров.

**Comment by Maksim8868** [comment]
If I understand correctly, the button is already on the screen. When you press it, a window opens, in which you need to click "save", it itself does not close and obscures all buttons in the future.

**Comment by Falcosc** [comment]
Oh, that's bad, it is difficult to automate the dialog as well.

Is your decision if you want to give it a try, or you can just wait 4-8 weeks for my update :)

**Comment by Falcosc** [comment]
@Maksim8868  just to make sure, you mean waypoint during track recording, are you?

Then this will be the function which I need to implement:
ActionBasics.actionTrackRecordAddWpt
add a new waypoint to current track record.
 * wptName  optional waypoint name
 * autoSave to automatically save waypoint without dialog

**Comment by Falcosc** [comment]
@Maksim8868 have a look on https://play.google.com/apps/testing/falcosc.locus.addon.tasker

Action Task Track Recording has abilities to add Waypoints
