### ISSUE TITLE
Get close point of track

### ISSUE THREAD

**Issue by Falcosc** [Falcosc/locus-addon-tasker#18]
@tortuosit how do you use your close position task? https://youtu.be/_7W2kzzaSxs?t=35 it seems painfully slow. Is there an useful use case where something like this does help?

Maybe it could be a lot faster if the track is reasonably long.

How did you implement this without get track points and without a get closed point of track function? And how did you find the track from the map?

Or does this have nothing to do with tracks? Because right after finding the first point you jump to an empty place in the map.

**Comment by tortuosit** [comment]
Oh sorry, you misinterpreted - it's just some useless random position thing unrelated to tracks! Just a random offset position (from map center). Sometimes I ask the gods of randomness for a raw hiking direction/target. Not really useful.
The point is calculated and displayed quickly, but Locus is the one who a) moves the map center and b) delays it (I have no influence on a and b). It's done via intent (geo:lat,lon)

**Comment by Falcosc** [comment]
Which action do you use to create the point?

You can try the new map move zoom (animated) task, it does support lon/lat as target. (Not sure if locus maps beta does already support it, it is only a few days old)

**Comment by tortuosit** [comment]
Thanks for your help.

> Which action for point creation is so slow? This looks a lot faster: https://www.youtube.com/watch?v=D66wa_qnWmU

OK, had a look at the code. The delay happens because there is a 1.5s wait command in the task.
