### ISSUE TITLE
track_rec_profile not returning anything

### ISSUE THREAD

**Issue by tortuosit** [Falcosc/locus-addon-tasker#19]
Hi Falco,

Req Sensors and Stats, %track_rec_profile, it's unset in Tasker, even though a recording is ongoing. On LM4 beta.

thx

**Comment by Falcosc** [comment]
Does documentation say anything about which values are expected?

**Comment by tortuosit** [comment]
Thx for your reply - solved. I had the stable branch version of your plugin installed after beta. But in this version, track_rec_profile is not present.
Re-installed beta again - works as intended.
