### ISSUE TITLE
Remove "run task" text? 

### ISSUE THREAD

**Issue by tortuosit** [Falcosc/locus-addon-tasker#21]
Hi Falco, the new version is awesome. So now since we use your plugin productively... can you allow to hide the informational text? After all it is just a waste of space for us... maybe just show message once?
best regards
Michael 

![Screenshot_20210630_085053](https://user-images.githubusercontent.com/9607631/123927425-2045e600-d98d-11eb-81e5-1ab5d9000985.jpg)

**Comment by Falcosc** [comment]
If we keep the title, we can place an X for close in the title to remove the buttom bar. And I could add a settings icon to promote the configuration of this dialog as 2nd title bar button.

Settings Name:
Compact Run Task Layout
> Hides hints about implementation and limited support

**Comment by tortuosit** [comment]
Thx, good idea. What I was meaning was also the descriptive text "This event is not properly configured..."

The plugin is so good. I use it at two places now. The quick bookmarks (Tasker secondary) for more position related and in the function buttons. This one uses one specific project and inside this project are decently named tasks, which basically just call other tasks. Kinda shortcuts.

**Comment by Falcosc** [comment]
@tortuosit could you please do some tests with the new Beta? Because the field documentation is waiting for this release.
