### ISSUE TITLE
[FR] Buttons instead of a task list

### ISSUE THREAD

**Issue by hawkeyexp** [Falcosc/locus-addon-tasker#34]
Hi, i'm using this plugin to control my multimedia playback during bike rides.
Depending on speed it starts and stops the playback :-)

In an extended version i made the controlled player selectable.
To changed the player from locus gui i added the plugin to the side menu with a filtered setup only showing my two tasks (they are setting only a variable).

It is working fine but to hit the correct task in the list is not always guaranteed if you only drive slowly and nut fully stopping.

It would be great to have a way bigger list or possible buttons in a matrix view.

**Comment by Falcosc** [comment]
I think you are talking about a Locus UI feature which is not able to be adjusted.
You can instead use a Tasker Dashboard to have a large button as overlay and control the visibility via your scripts.

**Comment by hawkeyexp** [comment]
Thx
