### ISSUE TITLE
Save parking spot with Tasker

### ISSUE THREAD

**Issue by miferber** [Falcosc/locus-addon-tasker#4]
It would be great if the following existing Tasker project would also be working with Locus Maps. 

https://www.xda-developers.com/how-to-save-your-parking-spot-with-tasker/

By means of  WearTasker I created a shortcut on my Wear OS watch to save the current parking location and a second which starts the navigation with Google Maps. So it would be great to replace it with Locus Maps. After that it would be possible to start the Locus Wear app and follow the navigation instruction on the watch

**Comment by Falcosc** [comment]
I guess the point which is missing is "tell Locus Maps to start Navigation to a custom position" because you can start Locus by Tasker and you did already record the position.
Is this correct?

**Comment by miferber** [comment]
Thanks for the reply!

Yes, that's correct. The location is stored in advance. I just copied the explanation from the above mentioned project

...."Because most of the time %LOC (Tasker’s global location variable) will have a value assigned to it already (last location fix), I only want to use the location coordinates requested through the profile. I will use the global variable %LastLocation to store these coordinates."....

**Comment by Falcosc** [comment]
I will have a look until next week if Locus does provide any API to start routing to a point. I know how to upload coordinates to Locus to create a Point and center it on map, but I am not sure about "start navigation".

I hope there is anything to add because my last update for this app is already over 3 months old because I did run out of use-cases.

**Comment by Falcosc** [comment]
Sorry for the delay, I will start after my 2 weeks vacation.

**Comment by Falcosc** [comment]
API call is working, I will publish 3 examples and close the ticket after weekend.
You can:
- Navigate to lon + lat
- Navigate to Adresstext (Online)
- Guide to lon + lat

**Comment by Falcosc** [comment]
Tasker can directly send intents to Locus. Here are 3 Examples:
- [Download Task GuideToPoint.tsk](https://raw.githubusercontent.com/Falcosc/locus-addon-tasker/master/examples/tasks/GuideToPoint.tsk.xml)
- [Download Task NavigateToAddress.tsk](https://raw.githubusercontent.com/Falcosc/locus-addon-tasker/master/examples/tasks/NavigateToAddress.tsk.xml)
- [Download Task NavigateToPoint.tsk](https://raw.githubusercontent.com/Falcosc/locus-addon-tasker/master/examples/tasks/NavigateToPoint.tsk.xml)

**Comment by miferber** [comment]
Thanks for the investigation!
