### ISSUE TITLE
Geotag function

### ISSUE THREAD

**Issue by jarstr** [Falcosc/locus-addon-tasker#7]
> How large is your tracks.db file? You may have to manually create index because of unknown limitations of taskers sqllite connector.

98MB. Now I copied it to dropbox, so I can share it for you (give me your email to not share it for public).

> I did add error output for you and I did extent the task with multible work folders in case of device specific permission problems. 

Not the error is obvious: <stdin> [1]: sqlite3: not found

How cat I get sqlite3 command for my android phone?

**Comment by Falcosc** [comment]
You could try to use Tasker SQLite Plugin as replacement for the run shell steps https://play.google.com/store/apps/details?id=com.jordanhotmann.taskersqliteplugin&hl=de
Tomorrow I will try it by my self and if this plugin can write to db file I will update the task.

You may notice that the main profile is using the much more stable "query" Task which is a build-in read only task which can't be used for index creation.

We don't need to share the track for this kind of error. My test db has 78MB without index and is still kind of usable. With index 88MB and really fast.

**Comment by Falcosc** [comment]
@jarstr don't use Tasker SQLite Plugin, it has complicated error handling.
I did just use plain java tasks to execute sql. Please check https://raw.githubusercontent.com/Falcosc/locus-addon-tasker/master/examples/tasks/Improve_Geotag_Performance.tsk.xml again and reopen ticket if this is still not working on your device. Would be nice to figure out what else could be different on your phone.

**Comment by jarstr** [comment]
It worked! My tracks.db grew up to 110MB. There is only one problem left when traying to geotag any photo copied to watched folder:

![Screenshot_20190615-100927_ASTRO File Manager](https://user-images.githubusercontent.com/10059260/59548960-51921b80-8f56-11e9-9f96-b7d01fa06626.jpg)

Unfortunately I can't change last part of directory path, so it has to contain spaces. When testing on directory without spaces in name (copying files manually) tasker seems to do something.

Another problem might be with timezone (I still have no one photo successfuly geotagged) but I have to check it more carefully.

**Comment by Falcosc** [comment]
Yes the example can't handle spaces. I will try to improve it, too. Should be easy to reproduce.
